apiVersion: v1
kind: Service
metadata:
  name: authentication-api
  labels:
    app: authentication-api
spec:
  ports:
    - name: http
      port: 8010
      targetPort: 8010
      protocol: TCP
  selector:
    app: authentication-api
  type: NodePort

